name: Secrets Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: Collect Secrets
      id: mmcdocker
      uses: mchirico/secrets-action@v1
      with:
        directory: "/home/runner/.credentials"
        id_rsa: ${{ secrets.SSH_PRIVATE_KEY }}
        user: ${{ secrets.USER }}
        server: ${{ secrets.SERVER }}
      env:
        INPUT_MILLISECONDS: 500

    - name: View Results
      id: view
      run: |
        pwd
        ls -lR "/home/runner/.credentials"

