name: Secrets Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Docker action step
      id: mmcdocker
      uses: mchirico/secrets-action@v1
      with:
        id_rsa: ${{ secrets.SSH_PRIVATE_KEY }}
        user: ${{ secrets.USER }}
        server: ${{ secrets.SERVER }}
      env:
        INPUT_MILLISECONDS: 500
